version: "3.7"

services:
  chromium:
    build:
      context: .
    container_name: chromium
    environment:
      - DISPLAY
      - PROXY
    volumes:
    - ${HOME}/volumes/chromium:/root/Downloads
    - ${XAUTHORITY}:/root/.Xauthority:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
#    entrypoint: /bin/bash -c "date; sleep 600"
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t


