version: "3.7"

services:
  chromium:
    image: chromium:latest
#    build:
#      context: .
    container_name: chromium
    environment:
      - DISPLAY
      - PROXY
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
    - ./chromium:/home/chromium
    - ${XAUTHORITY}:/home/chromium/.Xauthority:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    devices: 
    - /dev/dri:/dev/dri
#    user: "1000:1000"
#    entrypoint: chromium
    cap_add:
    - SYS_ADMIN
    network_mode: host
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t


